config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'pages/introduction'
  get 'pages/profile'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'pages/admin'
  get '/libraries/search', to: 'libraries#search'
  resources :libraries do
    resources :comments, only: [:index, :create]
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: [:edit, :update, :destroy]
  resources :notifications, only: :index
  delete 'destroy_all_notifications' => 'notifications#destroy_all'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :library

  has_many :notifications, dependent: :destroy
end

app/models/library.rb
class Library < ApplicationRecord
  validates :name, :address, :access, :study_space, :electrical_outlet, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user

  has_one_attached :avatar
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :notifications, dependent: :destroy

  def self.search(keyword)
    Library.where(["name LIKE ? or address LIKE ? or access LIKE? or detail LIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  def create_notification_like!(current_user)
    notification = current_user.active_notifications.new(
      library_id: id,
      visited_id: user_id,
      action: 'like'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    notification = current_user.active_notifications.new(
      library_id: id,
      comment_id: comment_id,
      visited_id: user_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :library
  belongs_to :user
  validates_uniqueness_of :library_id, scope: :user_id
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :library, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', optional: true
  belongs_to :visited, class_name: 'User', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :libraries
  has_one_attached :avatar
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_libraries, through: :likes, source: :library
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'guest_user'
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def already_liked?(library)
    likes.exists?(library_id: library.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @library = Library.find(params[:library_id])
    @comments = @library.comments
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @library = @comment.library
    if @comment.save
      @library.create_notification_comment!(current_user, @comment.id)
      flash[:success] = "コメントを登録しました"
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "コメントを登録できませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = "コメントを更新しました"
      redirect_to :pages_profile
    else
      flash[:danger] = "コメントを更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:danger] = "コメントを削除しました"
    redirect_to :pages_profile
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :library_id)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def new
    @library = Library.new
  end

  def create
    @library = current_user.libraries.new(library_params)
    if @library.save
      flash[:success] = "登録しました"
      redirect_to @library
    else
      flash[:danger] = "登録できませんでした"
      render "new"
    end
  end

  def show
    @library = Library.find(params[:id])
    @user = User.find_by(id: @library.user_id)
    if current_user
      @comment = current_user.comments.new
    end
    @like = Like.new
  end

  def search
    if params[:keyword].present?
      @libraries = Library.search(params[:keyword])
    end
  end

  def edit
    @library = Library.find(params[:id])
  end

  def update
    @library = Library.find(params[:id])
    if @library.update(library_params)
      flash[:success] = "更新しました"
      redirect_to @library
    else
      flash[:danger] = "更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @library = Library.find(params[:id])
    @library.destroy
    flash[:danger] = "削除しました"
    redirect_to :pages_profile
  end

  private

  def library_params
    params.require(:library).permit(:name, :address, :access, :study_space, :electrical_outlet, :avatar, :detail, :latitude, :longitude)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(library_id: params[:library_id])
    @library = Library.find(params[:library_id])
    @library.create_notification_like!(current_user)
    flash[:success] = "いいねしました"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(library_id: params[:library_id], user_id: current_user.id)
    @like.destroy
    flash[:danger] = "いいねを取り消しました"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.order('created_at DESC')
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy_all
    @notification = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @libraries = Library.all
  end

  def profile
    @libraries = current_user.libraries.all
    @comments = current_user.comments.all
    @likes = current_user.likes.all
  end

  def admin
    @user = User.all
    @libraries = Library.all
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i(update destroy)

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/views/comments/edit.html.erb
<div class="container container-fluid">
  <div class="row">
    <div class="library-register-box col-7 my-5 p-4">
      <div class="register-heading mb-4">
        <h5>コメント編集</h5>
      </div>
      <%= render "shared/error", obj: @comment %>
      <div class="update-content">
        <p>図書館名：<%= @comment.library.name %></p>
      </div>
      <%= form_with model: @comment do |f| %>
        <div class="update-content">
          <%= f.label :content, "コメント", class:"mb-2 required-a" %>
          <%= f.text_field :content, class:"form-control mb-4", placeholder:"#{@comment.content}"  %>
        </div>
        <div class="update-content">
          <div class="row justify-content-center">
            <%= f.submit "編集完了", class: "col-md-4 btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div class="container container-fluid registerd-libraries">
  <h4 class="page-head">コメント一覧<i class="fas fa-comment-dots comment-icon mx-2"></i></h4>
  <div class="row">
    <% if @comments.present? %>
        <table class="library-info">
          <tbody>
            <tr>
              <th class="col-lg-1 col-sm-2">ユーザー名</th>
              <th class="col-lg-11 col-sm-10">コメント</th>
            </tr>
            <% @comments.each do |comment| %>
              <tr>
                <td class="col-lg-1 col-sm-2"><%= comment.user.name %></th>
                <td class="col-lg-11 col-sm-10"><%= comment.content %></th>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% else %>
      <div class="no-library-notice">
        <p>コメントはありません</p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="notifications">
  <% flash.each do |key, value| %>
    <div class="alert-<%= key %> alert-<%= bootstrap_alert(key)%>">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryMap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/libraries/show.html.erb
<div class="container library-show">
  <div class="row">
    <div class="col-md-9 col-sm-12">
      <div class="library-image-box">
        <% if @library.avatar.attached? %>
          <%= image_tag @library.avatar, class: "library-image" %>
        <% else %>
          <%= image_tag 'no-image.png', class: "library-image" %>
        <% end %>
      </div>
      <div class="library-info-heading p-2 mt-2 d-flex justify-content-between">
        <h4><span class="px-4 py-2">図書館情報</span></h4>
        <div class="d-flex">
          <h6><i class="fas fa-heart like-icon px-4 mx-2"></i><span class="like-count"><%= @library.likes.count %></span></h6>
          <h6>
            <%= link_to library_comments_path(@library.id), class: 'comment-link' do %>
              <i class="fas fa-comment-dots comment-icon px-1 mx-2"></i>
            <% end %>
          </h6>
        </div>
      </div>
      <table class="library-info">
        <tbody>
          <tr>
            <th>図書館名</th>
            <td><%= @library.name %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td>
              <%= @library.address %>
              <div id="library-map"></div>
            </td>
          </tr>
          <tr>
            <th>アクセス</th>
            <td><%= @library.access %></td>
          </tr>
          <tr>
            <th>勉強スペース</th>
            <td><%= @library.study_space %></td>
          </tr>
          <tr>
            <th>コンセントの有無</th>
            <td><%= @library.electrical_outlet %></td>
          </tr>
          <tr>
            <th>詳細コメント</th>
            <td><%= @library.detail %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-3 col-sm-12">
      <div class="user-info pt-2 mt-2 col-md-12 col-sm-12">
        <div class="user-info-heading mt-2">
          <p><span class="px-4 py-2">登録者</span></p>
        </div>
        <% if @user.present? %>
          <div class="user-icon">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, class:"host-icon" %>
            <% else %>
              <%= image_tag 'default_icon.jpg', class:"host-icon" %>
            <% end %>
          </div>
          <div class="user-name pt-2">
            <p><%= @user.name %></p>
          </div>
        <% else %>
          <p>退会しました</p>
        <% end %>
      </div>
      <% if current_user&.admin? %>
        <div class="user-info pt-2 mt-2 col-md-12 col-sm-12">
          <div class="admin-authority mt-2">
            <p><span class="px-4 py-2">管理者権限</span></p>
          </div>
          <div class="edit-button ps-3 mb-2">
            <%= link_to "編集する",[:edit,@library], class: "edit-link" %>
          </div>
          <div class="delete-button ps-3 mb-2">
            <%= link_to "削除する", @library, method: :delete, data:{confirm:"本当に削除しますか"}, class: "delete-link" %>
          </div>
        </div>
      <% end %>
      <% if current_user %>
        <div class="user-info pt-2 pb-2 mt-2 col-md-12 col-sm-12 comment-sending sub-info">
          <p class='mt-2'><span class="px-4 py-2">いいね！</span></p>
          <% if current_user.already_liked?(@library) %>
            <%= link_to library_like_path(@library),method: :delete do %>
              <i class="fas fa-heart unlike-btn"></i>
            <% end %>
          <% else %>
            <%= link_to library_likes_path(@library), class: "like-link", method: :post do %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
          <% end %>
        </div>
        <div class="user-info pt-2 mt-2 col-md-12 col-sm-12">
          <div class="sub-info mt-2">
            <p><span class="px-4 py-2">コメントをしよう！</span></p>
            <%= form_with model: [@library, @comment], method: :post do |f| %>
              <% f.label :content, 'content' %>
              <%= f.text_area :content, rows: 10, class:"col-md-10 col-sm-10", placeholder: 'コメントを記入。' %>
              <%= f.hidden_field :library_id, value: @library.id %>
              <br>
              <%= f.submit '投稿',class: 'mt-2 mb-2 btn btn-primary' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  function initMap(){
    geocoder =  new google.maps.Geocoder()
    mapInstance = new google.maps.Map(document.getElementById('library-map'), {
      center: {
        lat: <%= @library.latitude %>,
        lng: <%= @library.longitude %>
      },
      zoom: 14
    });

    pos = new google.maps.LatLng(
      <%= @library.latitude %>,
      <%= @library.longitude %>
    );
    default_marker = new google.maps.Marker({
      map: mapInstance,
      position: pos
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhwT1YDk1ivaKA538KPwaNqFgkSSuJEkc&callback=initMap" async defer></script>

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>

<div class="user-view clearfix">
  <div class="d-flex align-items-center">
    <div class="user-icon">
      <% if visitor.avatar.present? %>
        <%= image_tag visitor.avatar, alt: "アイコン画像",class:"mx-2 p-1 header-host-icon" %>
      <% else %>
        <%= image_tag 'default_icon.jpg', alt: "アイコン画像", class:"mx-2 p-1 header-host-icon" %>
      <% end %>
    </div>
    <div class="notification">
      <span>
        <%= visitor.name %>さんが
        <% case notification.action %>
          <% when 'like' then %>
            あなたの登録した<%= link_to notification.library.name, library_path(notification.library.id) %>にいいねしました。
          <% when 'comment' then %>
            あなたの登録した<%= link_to notification.library.name, library_path(notification.library.id) %>にコメントしました。<br>
        <% end %>
      </span>
    </div>
    <div class="notification-time">
      <span class="small text-muted text-right">(<%= time_ago_in_words(notification.created_at).upcase %>前)</span>
    </div>
  </div>
  <div class="comment-content px-5">
    <span class="text-muted"><%= Comment.find_by(id: notification.comment_id)&.content %></span>
  </div>
  <hr>
</div>

app/views/notifications/index.html.erb
<div class="container container-fluid">
  <div class="row">
    <h3 class="text-center mt-3">通知一覧</h3>
    <%= link_to destroy_all_notifications_path, method: :delete do %>
      <i class="fas fa-trash" style="color: black;"></i>
      <h7 style="color: black;">全削除</h7>
    <% end %>
    <hr>
    <% if @notifications.exists? %>
      <div class="users-index">
        <%= render @notifications %>
      </div>
    <% else %>
      <p>通知はありません</p>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="top">
  <div class="top-main">
    <div class="container">
    </div>
  </div>
  <div id="gmap">
    <h2>Library map</h2>
  </div>
  <div id="map"></div>
</div>
  
<script>
  function initMap(){
    geocoder =  new google.maps.Geocoder()
    mapInstance = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: 35.681, 
        lng: 139.767
      },
      zoom: 11
    });
    <% @libraries.each do |library| %>
      (function(){
        let pos = new google.maps.LatLng(
          <%= library.latitude %>,
          <%= library.longitude %>
        );
        let infoWindow = new google.maps.InfoWindow({
          content: '<%= link_to "#{library.name}", library_path(library.id) %>'
        });
      
        let default_marker = new google.maps.Marker({
          map: mapInstance,
          position: pos
        });
        
        default_marker.addListener("click", function(){
          infoWindow.open(map, default_marker);
        });
      })();
    <% end %>
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials[:gmap][:api_key] %>&callback=initMap" async defer></script>

app/views/pages/profile.html.erb
<div class="container container-fluid profile-page">
  <div class="row">
    <div class="col-md-3 col-sm-12">
      <div class="user-info pt-2 pb-2 mt-5 col-md-12 col-sm-12">
        <div class="library-info-heading p-2 mt-2">
          <h6><span class="px-4 py-2">ユーザー情報</span></h4>
        </div>
        <div class="user-icon">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class:"host-icon" %>
          <% else %>
            <%= image_tag 'default_icon.jpg', class:"host-icon" %>
          <% end %>
        </div>
        <div class="user-name pt-2">
          <p><%= current_user.name %></p>
        </div>
        <div class="user-emai">
          <p><%= current_user.email %></p>
        </div>
        <div class="edit-button">
          <%= link_to "ユーザー情報編集", :edit_user_registration %>
        </div>
        <% if current_user.admin? %>
          <div class="admin-button pt-2">
            <%= link_to "管理者権限", :pages_admin %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-9 col-sm12 registerd-libraries">
      <h4 class="page-head pb-2">登録済み図書館</h4>
      <div class="row">
        <% if @libraries.present? %>
          <% @libraries.each do |library| %>
            <div class="col-sm-6 col-md-5 col-lg-4">
              <div class="libraries-frame-inner">
                <%= link_to library do %>
                  <div class="libraries-image-frame">
                    <% if library.avatar.attached? %>
                      <%= image_tag library.avatar, class: "libraries-image" %>
                    <% else %>
                      <%= image_tag 'no-image.png', class: "libraries-image" %>
                    <% end %>
                  </div>
                  <div class="libraries-information pt-3 px-3">
                    <p class="libraries-name mb-2"><%= library.name %></p>
                    <p class="libraries-address mb-2"><%= library.address %></p>
                  </div>
                <% end %>
                <div class="edit-button ps-3 mb-2">
                  <%= link_to "編集する",[:edit,library], class: "edit-link" %>
                </div>
                <div class="delete-button ps-3 mb-2">
                  <%= link_to "削除する", library, method: :delete, data:{confirm:"本当に削除しますか"}, class: "delete-link" %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="no-library-notice">
            <p>登録済みの図書館はありません</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-10 col-sm12 registerd-libraries">
      <h4 class="page-head pb-2">コメント一覧<i class="fas fa-comment-dots comment-icon mx-2"></i></h4>
      <div class="row">
        <% if @comments.present? %>
        <table class="comment-like-info">
          <tbody>
            <tr>
              <th class="col-md-2 col-sm-2">図書館名</th>
              <th class="col-md-8 col-sm-8">コメント</th>
              <th colspan="2",class="col-md-2 col-sm-2">編集</th>
            </tr>
            <% @comments.each do |comment| %>
              <tr>
                <td class="col-md-2 col-sm-2 link-item"><%= link_to comment.library.name, library_path(comment.library.id), class: 'link-item' %></td>
                <td class="col-md-8 col-sm-8"><%= comment.content %></td>
                <td class="col-md-1 col-sm-1"><%=link_to "編集", edit_comment_path(comment.id) %></td>
                <td class="col-md-1 col-sm-1"><%=link_to "削除", comment, method: :delete, data:{confirm:"本当に削除しますか"}, class: "delete-link" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <div class="no-library-notice">
            <p>コメントはありません</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-10 col-sm12 registerd-libraries">
      <h4 class="page-head pb-2">いいねした図書館<i class="fas fa-heart like-icon mx-2"></i></h4>
      <div class="row">
        <% if @likes.present? %>
          <table class="comment-like-info">
            <tbody>
              <tr>
                <th class="col-md-2">図書館名</th>
                <th class="col-md-4">住所</th>
                <th class="col-md-2">アクセス</th>
                <th class="col-md-2">勉強スペース</th>
                <th class="col-md-2">コンセントの有無</th>
              </tr>
              <% @likes.each do |like| %>
                <tr>
                  <%= link_to library_path(like.library_id) do %>
                    <td class="col-md-2 link-item"><%= link_to like.library.name, library_path(like.library_id), class: 'link-item' %></td>
                    <td class="col-md-4"><%= like.library.address %></td>
                    <td class="col-md-2"><%= like.library.access %></td>
                    <td class="col-md-2"><%= like.library.study_space %></td>
                    <td class="col-md-2"><%= like.library.electrical_outlet %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <div class="no-library-notice">
            <p>いいねした図書館はありません</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div> 

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p>© 2021 Library Map</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark ">
  <div class="container-fluid">
    <%= link_to "Library map for study", :root ,class:"header-logo navbar-brand mb-0 h1" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if current_user %>
      <div class="collapse navbar-collapse bg-dark" id="navbarNav">
        <ul class="navbar-nav ms-auto nav-list">
          <li class="nav-item">
            <%= link_to "Map", pages_home_path(anchor: "gmap"), {class: "nav-link"} %>
          </li>
          <li class="nav-item">
            <%= link_to "図書館登録", :new_library, {class: "nav-link"} %>
          </li>
          <li class="nav-item">
            <%= link_to "図書館一覧", :libraries, {class: "nav-link"}  %>
          </li>
          <li class="nav-item">
          <%= link_to "ログアウト", :destroy_user_session, {method: :delete, class: "nav-link"}  %>
          </li>
          <li class="nav-item">
            <%= link_to notifications_path, class: "btn-default" do %>
              <span class="fa-stack nav-link">
                <i class="fas fa-bell fa-stack-2x bell align-bottom"></i>
                <% if current_user.passive_notifications.where(checked: false).any? %>
                  <i class="fa fa-circle fa-stack-1x mx-2 notification-mark"></i>
                <% end %>
              </span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "/pages/profile", {class:"nav-link"} do %>
              <% if current_user.avatar.present? %>
                <%= image_tag current_user.avatar, alt: "アイコン画像",class:"header-host-icon" %>
              <% else %>
                <%= image_tag 'default_icon.jpg', alt: "アイコン画像", class:"mx-3 p-1 header-host-icon" %>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="collapse navbar-collapse ms-auto" id="navbarNav">
        <ul class="navbar-nav ms-auto nav-list">
          <li class="nav-item">
            <%= link_to "Library map for studyとは", :pages_introduction, {class: "nav-link mx-3 my-2"} %>
          </li>
          <li class="nav-item">
            <%= link_to "Map", pages_home_path(anchor: "gmap"), {class: "nav-link mx-3 my-2"} %>
          </li>
          <li class="nav-item">
            <%= link_to "図書館一覧", :libraries, {class: "nav-link mx-3 my-2"}  %>
          </li>
          <li class="nav-item">
            <%= link_to '新規登録', :new_user_registration, {class:"nav-link mx-3 my-2"} %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', :new_user_session, {class:"nav-link mx-3 my-2"} %>
          </li>
          <li class="nav-item">
            <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class:"nav-link mx-3 my-2", method: :post %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>